# For technical reasons, this file is not reloaded automatically when you run the command
# 'bundle exec jekyll serve'. If you change this file, you have to restart the server process.

# https://github.com/jekyll/jekyll/issues/7478
theme: null

exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "vendor/bundle"

defaults:
  - scope:
      path: ""
    values:
      layout: layout
